export const ADD_TODO = 'ADD_TODO';
export const TOGGLE_TODO_COMPLETE = 'TOGGLE_TODO_COMPLETE';
export const TOGGLE_TODO_DELETE = 'TOGGLE_TODO_DELETE';

export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';
